# Generated by Django 5.2.11 on 2026-04-24 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do projeto, você poderá alterar depois!",
                        max_length=150,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("ARQUIVADO", "Arquivado"),
                            ("ENCERRADO", "Encerrado"),
                        ],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ManyToManyField(
                        related_name="arquivos", to="reqManager.projeto"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegraDeNegocio",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(editable=False, max_length=10)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_ANALISE", "Em análise"),
                            ("APROVADO", "Aprovado"),
                            ("IMPLEMENTADO", "Implementado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=15,
                    ),
                ),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras",
                        to="reqManager.arquivo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Requisito",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RF", "Requisito Funcional"),
                            ("RNF", "Requisito Não Funcional"),
                            ("RN", "Regra de Negócio"),
                        ],
                        max_length=3,
                    ),
                ),
                ("codigo", models.CharField(editable=False, max_length=10)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Média"),
                            ("BAIXA", "Baixa"),
                        ],
                        default="MEDIA",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_ANALISE", "Em análise"),
                            ("APROVADO", "Aprovado"),
                            ("IMPLEMENTADO", "Implementado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=15,
                    ),
                ),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos",
                        to="reqManager.arquivo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequisitoDadosRF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ator_envolvido", models.CharField(blank=True, max_length=150)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regras",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requisitos_funcionais",
                        to="reqManager.regradenegocio",
                    ),
                ),
                (
                    "requisito",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_rf",
                        to="reqManager.requisito",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequisitoDadosRNF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("DESEMPENHO", "Desempenho"),
                            ("SEGURANCA", "Segurança"),
                            ("USABILIDADE", "Usabilidade"),
                            ("DISPONIBILIDADE", "Disponibilidade"),
                            ("ESCALABILIDADE", "Escalabilidade"),
                            ("MANUTENCAO", "Manutenibilidade"),
                            ("PORTABILIDADE", "Portabilidade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisito",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_rnf",
                        to="reqManager.requisito",
                    ),
                ),
            ],
        ),
    ]
