# Generated by Django 5.2.11 on 2026-05-08 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regradenegocio',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='requisito',
            options={'ordering': ['codigo']},
        ),
        migrations.RemoveField(
            model_name='requisitodadosrf',
            name='regras',
        ),
        migrations.AddField(
            model_name='regradenegocio',
            name='requisito_funcional',
            field=models.ForeignKey(blank=True, help_text='Requisito Funcional ao qual esta regra está vinculada (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_vinculadas', to='reqManager.requisito'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(help_text='Ex.: Módulo de Login', max_length=150),
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='projeto',
        ),
        migrations.AlterField(
            model_name='requisito',
            name='tipo',
            field=models.CharField(choices=[('RF', 'Requisito Funcional'), ('RNF', 'Requisito Não Funcional')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='regradenegocio',
            unique_together={('arquivo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='requisito',
            unique_together={('arquivo', 'codigo')},
        ),
        migrations.AddField(
            model_name='arquivo',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='reqManager.projeto'),
            preserve_default=False,
        ),
    ]
